### ISSUE TITLE
Logger & PostImporter Errors

### ISSUE THREAD

**Issue by lkitto** [gastate/DALN#12]
1. Verify log4j is properly configures and that config files are included in repo.  Could you make sure that the xml file for it is also in the repo? 
2. App is crashing when posts are empty.  It throws an out of bounds exception in PostImporter on the following line:

//GETTING POST INFO//
Element postDataRoot = postInfoRoot.child(0).child(0).child(0);

Error is below.

log4j:WARN No appenders could be found for logger (PostImporter).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                at java.util.ArrayList.rangeCheck(ArrayList.java:635)
                at java.util.ArrayList.get(ArrayList.java:411)
                at org.jsoup.nodes.Element.child(Element.java:200)
                at PostImporter.doImport(PostImporter.java:175)
                at PostImporter.<init>(PostImporter.java:96)

**Comment by ShakibAhmed** [comment]
For #1, there is a log4j.properties file that is located under DALN/production/java. #2 should be fixed with latest commit
